### ISSUE TITLE
Adt alarm enabled/disabled fromADT control panel

### ISSUE THREAD

**Issue by wxman60** [rlippmann/hass-adtpulse#6]
@rlippmann  When we enable our ADT alarm form the ADT control panel it doesn't update on the Home Assistant ADT card. Only a restart of home assistant clears the issue.  If it is done from the ADT mobile app the card updates as it should. Any help would be appreciated.

**Comment by rlippmann** [comment]
I just saw this.  Does the alarm arm and disarm from HA?

**Comment by wxman60** [comment]
Yes, it does. If you ar/disarm from the ADT app on phone the dashboard in HA updates. Just when you arm/disarm it from the ADT control panel itself is when HA does not update the HA card on the dashboard.

**Comment by rlippmann** [comment]
So, to clarify, if you arm/disarm in HA, the dashboard updates.  Also, if you arm/disarm in the mobile app/website, the dashboard updates.  It's just when you use the actual keypad that it doesn't?

**Comment by wxman60** [comment]
That is correct. I can even run automations and it works and updates the dashboard. Only when enabling or disabling via the ADT control panel the HA dashboard doesn't update. If it do a restart on HA then it will show the correct status.

**Comment by wxman60** [comment]
Any update that you can provide?

**Comment by rlippmann** [comment]
I've been re-working the entire codebase that goes underneath the integration to try and make it more resilient to errors for the last month of so.  It's (hopefully) almost ready for release.  I did some limited testing with the new version, and it appears to work for this case.  But I want to make sure the rest of the code does what it's supposed to, first.

**Comment by wxman60** [comment]
Thanks for the update. Appreciate all the effort.

**Comment by rlippmann** [comment]
I think this is fixed in 0.4.0
